language: csharp
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g
mono:
  - 4.2.1
os:
  - linux
branches:
  only:
    - master
    - dev
script:
  - ./build.sh --quiet build-all
env:
  - KOREBUILD_TEST_SKIPMONO=1
